project_name: vanity-ssh-keygen

before:
  hooks:
    - go mod tidy
    - go mod download

release:
  disable: true

builds:
  - main: ./cmd/vanity-ssh-keygen
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: amd64
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s -w -X main.version={{.Version}}
    flags:
      - -trimpath

kos:
  - main: ./cmd/vanity-ssh-keygen
    tags:
      - "{{.Version}}"
      - latest
    ldflags:
      - -s -w -X main.version={{.Version}}
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    bare: true
    creation_time: "{{.CommitTimestamp}}"
    ko_data_creation_time: "{{.CommitTimestamp}}"

    platforms:
      - linux/amd64
      - linux/arm64

sboms:
  - artifacts: archive

archives:
  - format: binary
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"

checksum:
  name_template: "sha256sums.txt"
  algorithm: sha256

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  skip: true
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^hack:"
