project_name: vanity-ssh-keygen

before:
  hooks:
  - go mod tidy
  - go mod download

builds:
- main: ./cmd/vanity-ssh-keygen/main.go
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
  mod_timestamp: '{{ .CommitTimestamp }}'
  ldflags:
  - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.CommitDate}} -X main.builtBy=goreleaser
  flags:
  - -trimpath

archives:
- format: binary
  name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"

checksum:
  name_template: 'sha256sums.txt'
  algorithm: sha256

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^hack:'

#dockers:
#- image_templates:
#  #- "{{.ProjectName}}:latest"
#  - "{{.ProjectName}}:{{ .Version }}-amd64"
#  skip_push: true
#  dockerfile: goreleaser.Dockerfile
#  use_buildx: true
#  build_flag_templates:
#  - --pull
#  - --platform=linux/amd64
#  - --label=org.opencontainers.image.created={{.Date}}
#  - --label=org.opencontainers.image.title={{.ProjectName}}
#  - --label=org.opencontainers.image.revision={{.FullCommit}}
#  - --label=org.opencontainers.image.version={{.Version}}
