project_name: vanity-ssh-keygen
version: 2

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: vanity-ssh-keygen
    main: ./cmd/vanity-ssh-keygen
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: amd64
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s -w -X main.version={{.Version}}
    flags:
      - -trimpath

kos:
  - build: vanity-ssh-keygen
    tags:
      - "{{.Version}}"
      - latest
    bare: true
    creation_time: "{{.CommitTimestamp}}"
    ko_data_creation_time: "{{.CommitTimestamp}}"

    platforms:
      - linux/amd64
      - linux/arm64

docker_signs:
  - cmd: cosign
    artifacts: manifests
    output: true
    args:
      - "sign"
      - "${artifact}"
      - "--yes"

sboms:
  - artifacts: archive

archives:
  - formats:
      - binary

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^hack:"
